version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - REDIS_HOST=redis
    labels:
      traefik.enable: "true"
      traefik.http.routers.meetme.rule: "Host(`quando.events`, `www.quando.events`)"
      traefik.http.routers.meetme.entrypoints: "https"
      traefik.http.routers.meetme.tls: "true"
      traefik.http.services.meetme.loadbalancer.server.port: "3000"
    networks:
      - default
      - traefik

  redis:
    image: redis:latest
    expose:
      - 6379
    volumes:
      - ./redis-data:/data

networks:
  traefik:
    external: true
    name: traefik_proxy