services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 3000
    restart: unless-stopped
    depends_on:
      redis:
        condition: service_started
    environment:
      - NODE_ENV=production
      - PORT=3000
      - NUXT_REDIS_HOST=redis
    labels:
      traefik.enable: "true"
      traefik.http.routers.meetme.rule: "Host(`quando.filippo-orru.com`)"
      traefik.http.routers.meetme.entrypoints: "https"
      traefik.http.routers.meetme.tls: "true"
      traefik.http.services.meetme.loadbalancer.server.port: "3000"
      kuma.quandoevents.http.name: "Quando Events"
      kuma.quandoevents.http.url: "https://quando.filippo-orru.com"
    networks:
      - default
      - traefik

  redis:
    image: redis:latest
    restart: unless-stopped
    expose:
      - 6379
    volumes:
      - ./redis-data:/data

networks:
  traefik:
    external: true
    name: traefik_proxy
